working on lb

diff --git a/lb b/lb
--- a/lb
+++ b/lb
@@ -24,10 +24,10 @@ newpost() { read -erp "Give a title for your post:
 	" title
 	echo "$title" | grep -q "\"" && printf "Double quotation marks (\") are not allowed in entry titles.\\n" && exit
 	url="$(echo "$title" | iconv -cf UTF-8 -t ASCII//TRANSLIT | tr -d '[:punct:]' | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | sed "s/-\+/-/g;s/\(^-\|-\$\)//g")"
-	echo "AddDescription \"$title\" \"$url.html\"" >>  "$archivefile"|| { echo "Error: Is $archivefile writeable?"; exit; }
-	( [ -f "$webdir/.drafts/$url/$url.html" ] || [ -f "$webdir/$url/$url.html" ] ) && echo "There is already an existing draft or post of that same name/URL." && exit
+	echo "AddDescription \"$title\" \"$url.md\"" >>  "$archivefile"|| { echo "Error: Is $archivefile writeable?"; exit; }
+	( [ -f "$webdir/.drafts/$url/$url.md" ] || [ -f "$webdir/$url/$url.md" ] ) && echo "There is already an existing draft or post of that same name/URL." && exit
 	mkdir -p "$webdir/.drafts/$url";
-	$EDITOR "$webdir/.drafts/$url/$url.html" ;}
+	$EDITOR "$webdir/.drafts/$url/$url.md" ;}
 
 listandReturn() {
 	printf "Listing contents of %s\\n" "$1"
@@ -48,7 +48,7 @@ publish() { \
 	webdate="$(date '+%a, %d %b %Y %H:%M:%S %z')" # But this visible date you can set to any format.
 	tmpdir=$(mktemp -d)
 	$(cp -r "$webdir/.drafts/$basefile" "$webdir/$webtarget/posts/")
-	printf "<div class='entry'>\\n<h2 id='%s'>%s</h2>\\n<small>[<a href='%s'>standalone</a>]</small>\\n%s\\n<small>%s</small>\\n</div>\\n" "$base" "$realname" "$webdir/$webtarget/posts/$basefile/$basefile.html" "$(cat "$webdir/.drafts/$basefile/$basefile.html")" "$webdate" > "$tmpdir/html"
+	printf "<div class='entry'>\\n<h2 id='%s'>%s</h2>\\n<small>[<a href='%s'>standalone</a>]</small>\\n%s\\n<small>%s</small>\\n</div>\\n" "$base" "$realname" "$webdir/$webtarget/posts/$basefile/$basefile.md" "$(cat "$webdir/.drafts/$basefile/$basefile.md")" "$webdate" > "$tmpdir/html"
 	printf "<li>%s &ndash; <a href=\"%s\">%s</a></li>\\n" "$(date '+%Y %b %d')" "$webdir/$webtarget/posts/$basefile/$basefile.html" "$realname" > "$tmpdir/index"
 	sed -i "/<!-- LB -->/r $tmpdir/html" "$blogfile"
 	sed -i "/<!-- LB -->/r $tmpdir/index" "$indexfile"
